config/routes.rb
Rails.application.routes.draw do
  get '/logout', :to => 'session#destroy', :as => :logout
  get '/auth/:provider/callback', :to => 'session#create'
  get '/login', :to => redirect('/auth/cas/'), :as => :login
  get '/auth/failure', :to => 'session#failure'
  get '/portal', :to => 'session#new', :as => :portal

  resources :scans, :controller => "scan"

  get '/users', :to => 'user#index'
  get '/users/:id', :to => 'user#show', :as => 'user'
  get '/users/become/:id/', :to => 'user#become'

  root 'scan#new'

end

app/models/address.rb
require 'ipaddr'

class Address
  include ActiveAttr::Model

  attribute :address, :type => String
  attribute :location, :type => String, :default => "No Location Given"

  @@all_addresses = []

  def initialize(attributes={})
    super
    @@all_addresses << self
  end

  def self.all
    @@all_addresses
  end

  def self.find(ip)
    begin
      add = IPAddr.new(ip)
    rescue
      raise RangeError # if ip is not actually an IP
    end

    Address.all.each do |a|
      range = IPAddr.new(a.address)
      if range.include?(add)
        return a # If it is in a range, then we return that.
      end
    end
    return nil # Else we return nil
  end
end

f = YAML::load_file(File.join(Rails.root, 'config/targets.yml'))
f["Addresses"].each do |location, addresses|
  addresses.each do |ip|
    Address.new(address: ip, location: location)
  end
end

app/models/scan.rb
class AddressValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    begin
      valid = Address.find(value)
      if valid.nil?
        record.errors.add(attribute, "is not a whitelisted address")
      end
    rescue
      record.errors.add(attribute, "is not a valid address")
    end
  end
end

class TimeValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    begin
      if value.past?
        record.errors.add(attribute, "is in the past")
      end
    rescue NoMethodError
      record.errors.add(attribute, "can't be blank")
    end
  end
end

class Scan < ActiveRecord::Base
  validates :user, presence: true
  validates :targets, presence: true, address: true
  validates :time, presence: true, time: true
  validates :policy, presence: true

  def self.export!
    # Looks for all scans that are ready to be sent off.
    # Then sends them out through the API.
    right_now = Time.zone.now()
    results = []
    Scan.all.each do |s|
      if s.time <= right_now and s.uuid == nil
        results << s
      end
    end
    if Nessus.createSession
      results.each do |scan|
        scan.uuid = Nessus.createScan(scan.targets, "Scan ##{scan.id}")
        Rails.logger.warn "Scan ##{scan.id} exported! - UUID: #{scan.uuid}"
        scan.save(:validate => false)
      end
      Nessus.killSession
    end
  end

  def getResults!
    # Looks for the results for the given scan.
    if Nessus.createSession
      xml = Nessus.getScanResults(self.uuid)
    end
    Nessus.killSession
    return xml
  end
end

app/models/user.rb
class User
  include ActiveAttr::Model

  attribute :id, :type => Integer
  attribute :name, :type => String
  attribute :calnet, :type => Integer
  attribute :email, :type => String
  attribute :admin, :type => Boolean, :default => false

  @@all_users = []

  def initialize(attributes={})
    super
    @@all_users<< self
    self.id = @@all_users.length - 1
  end

  def admin?
    return admin
  end

  def self.find_by_calnet(uid)
    Rails.logger.info "Trying to find User UID #{uid}..."
    @@all_users.each do |user|
      Rails.logger.debug "Does #{user.calnet} == #{uid}?"
      if user.calnet == uid
        return user
      end
    end
    return nil
  end

  def self.find(id)
    @@all_users[id.to_i]
  end

  def self.all
    @@all_users
  end
end

f = YAML::load_file(File.join(Rails.root, 'config/users.yml'))
f["Users"]["Standard"].each do |name, values|
  User.new(name: name, calnet: values["calnet"], email: values["email"])
end
f["Users"]["Admin"].each do |name, values|
  User.new(name: name, calnet: values["calnet"], email: values["email"], admin: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_filter :check_sign_in

  def current_user
    @current_user ||= User.find_by_calnet(session[:user_id])
  end

  def check_sign_in
    current_user
    unless @current_user
      redirect_to portal_path
    end
  end
end

app/controllers/scan_controller.rb
class ScanController < ApplicationController
  def index
    @scans = Scan.all
    authorize @scans
  end

  def new
    @scan = Scan.new
  end

  def create
    s_params = scan_params # Strong params

    begin
      s_params[:time] = Time.zone.parse(s_params[:time])
    rescue
      s_params[:time] = "" # If a ill-formatted time is given - XSS attempt, most likely
    end
    s_params[:user] = @current_user.calnet

    @scan = Scan.new s_params
    Rails.logger.debug "Attempting to create new scan..."
    Rails.logger.debug @scan.inspect
    if @scan.save
      Rails.logger.warn "Scan ##{@scan.id} created!"
      flash[:success] = "<b>Scan successfully created!</b> Check your user page for more information!"
      redirect_to edit_scan_path(@scan)
    else
      Rails.logger.debug "Creation failed!"
      Rails.logger.debug @scan.errors.full_messages
      flash[:error] = "<b>Oops!</b> There were some problems with your scan:"
      @scan_errors = @scan.errors.full_messages or []
      render :action => 'new'
    end
  end

  def edit
    @scan = Scan.find params[:id]
    if @scan.uuid
      # Get results
      @results = @scan.getResults!
    end
    authorize @scan
  end

  def update
    @scan = Scan.find params[:id]
    authorize @scan
    begin
      params[:time] = Time.zone.parse(s_params[:time])
    rescue
      params[:time] = "" # If a ill-formatted time is given - XSS attempt, most likely
    end
    Rails.logger.debug "Attempting to update Scan ##{@scan.id}..."
    Rails.logger.debug @scan.inspect
    if @scan.uuid
      Rails.logger.warn "Scan##{@scan.id} has already been exported."
      redirect_to_edit_scan_path(@scan)
    elsif @scan.update_attributes scan_update_params
      Rails.logger.warn "Scan ##{@scan.id} updated!"
      Rails.logger.debug @scan.inspect
      redirect_to edit_scan_path(@scan)
    else
      Rails.logger.debug "Updating failed!"
      Rails.logger.debug @scan.errors
      render :action => :edit
    end
  end

  def destroy
    @scan = Scan.find params[:id]
    authorize @scan
    @scan.destroy
    Rails.logger.warn "Scan ##{@scan.id} destroyed!"
    redirect_to scans_path
  end

  private
    def scan_params
      params.require(:scan).permit(:targets, :time)
    end

    def scan_update_params
      params.require(:scan).permit(:targets, :time, :policy)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_filter :check_sign_in

  def new
  end

  def create
    auth_hash = request.env['omniauth.auth']
    session[:user_id] = auth_hash[:uid].to_i
    current_user
    if @current_user
      Rails.logger.info "Authenticated as #{@current_user.name}!"
      redirect_to '/'
    else
      Rails.logger.info "Not authorized."
      flash[:login] = "Your Calnet is not authorized to access OnDemand - please contact Information Security for access."
      redirect_to '/'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to 'https://auth.berkeley.edu/cas/logout'
  end

  def failure
    render status: 417
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    authorize @current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    authorize @user
    @scans = Scan.where(:user => @user.calnet)
  end

  def become
    authorize @current_user
    session[:user_id] = params[:id].to_i
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scan_helper.rb
module ScanHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    title Scan OnDemand
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  body
    - if content_for?(:navbar)
      = yield(:navbar)
    - if content_for?(:flashes)
      = yield(:flashes)
    = yield

    div class="modal fade about-modal" tabindex="-1" role="dialog" aria-hidden="true"
      div class="modal-dialog modal-lg"
        div class="modal-content"
          div class="modal-header"
            button type="button" class="close" data-dismiss="modal" aria-hidden="true" &times;
            h4 class="modal-title" id="aboutLabel" About OnDemand
          div class="modal-body"
            p OnDemand is an application created by SA-IT's Information Security team. Its goal is to provide users within UC Berkeley to actively scan and analyze their own systems.
            p If you need help using OnDemand, email the team at security@rescomp.berkeley.edu
          div class="modal-footer"
            button type="button" class="btn btn-default" data-dismiss="modal" Close

app/views/layouts/scan.slim
- content_for :navbar do
    header class="navbar navbar-default" role="navigation"
      div class="container-fluid"
        div class="navbar-header"
          button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapsed-navbar"
            span class="sr-only" Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          = link_to "OnDemand", root_path, class: "navbar-brand"
        div class="collapse navbar-collapse" id="collapsed-navbar"
          div class="navbar-left"
            ul class="nav navbar-nav"
              li class="active"
                a href="#" data-toggle="modal" data-target=".about-modal" About
          div class="navbar-right"
            ul class="nav navbar-nav"
              li class="dropdown"
                - @name = "Nobody"
                - @user = User.find_by_calnet(session[:user_id])
                - if @user
                  - @name = @user.name
                a href="#" class="dropdown-toggle" data-toggle="dropdown"
                  = "Signed in as #{@name}"
                  b class="caret"
                ul class="dropdown-menu"
                  li
                    = link_to "My Profile", user_path(@current_user.id)
                  li
                    = link_to "Logout", logout_path
                  - if @current_user.admin?
                      li role="presentation" class="divider"
                      li
                        = link_to "All Scans", scans_path
                      li
                        = link_to "All Users", users_path
                      li
                        = link_to "View As John Doe", "/users/become/1"

- content_for :flashes do
    - if flash[:success]
      div class="alert alert-success alert-dismissable"
        button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;
        = flash[:success].html_safe
    - if flash[:error]
      div class="alert alert-danger alert-dismissable"
        button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;
        = flash[:error].html_safe
        ul
          - if @scan_errors.nil? then @scan_errors = [] end
          - @scan_errors.each do |e|
            li
              = e
    - if flash[:login]
      div class="alert alert-danger alert-dismissable"
        button type="button" class="close" data-dismiss="alert" aria-hidden="true" &times;
        = flash[:login]

= render template: "layouts/application"

app/views/layouts/user.slim
= render template: "layouts/scan"

app/views/scan/edit.slim
div class="container"
    div class="panel panel-default"
      div class="panel-heading" 
        h3 class="panel-title" Viewing Scan...
      div class="panel-body"
        = form_for @scan do |s|
            table class="table"
              thead
                tr
                  th Information
                  th 
              tbody
                tr
                  td
                    strong Requested by...
                  td
                    - user = User.find_by_calnet(@scan.user)
                    = link_to user.name, user_path(user.id)
                tr
                  td
                    strong Targets...
                  td
                    = s.text_field :targets, :class => "form-control"
                tr
                  td
                    strong Scheduled for...
                  td
                    = s.text_field :time, :value => @scan.time.to_s, :class => "form_datetime date form-control"
                - if @scan.results
                  tr
                    td
                      strong Had a risk level of...
                    td
                      = @scan.results
            p
              - if !@scan.uuid
                = s.submit "Update!", :class => "btn btn-primary btn-lg btn-block"
    - if @results
      div class="panel panel-default"
        div class="panel-heading"
          h3 class="panel-title" Vulnerabilites
          p Please allow ten minutes for scan to complete!
        div class="panel-body"
          table class="table"
            thead
              tr
                th Plugin Name
                th Severity
            tbody
              - @results.each do |v|
                tr
                  td
                    = link_to v['name'], v['url']
                  td
                    = v['severity']

app/views/scan/index.slim
div class="container"
    div class="panel panel-default"
      div class="panel-heading" 
        h3 class="panel-title" Requested Scans
      div class="panel-body"
       table class="table table-striped"
         thead
           tr
             th #
             th Address
             th Requestor
         tbody
           - @scans.each do |s|
             tr
               td 
                 = s.id
               td 
                 - begin
                     = link_to Address.find(s.targets).location, edit_scan_path(s)
                 - rescue
                     = link_to "Unknown Location", edit_scan_path(s)
               td 
                 - user = User.find_by_calnet(s.user)
                 = link_to user.name, user_path(user.id)

app/views/scan/new.slim
div class="container"

  div class="form-container"
    = form_for @scan do |s|
      <p>
        div class="input-group"
          = s.text_field :targets, :class => "form-control", :placeholder => "Input a Berkeley IP - net masks are OK!"
          i class="fa fa-desktop fa-fw input-group-addon"
      </p>
      <p>
        div class="input-group"
          = s.text_field :time, :class => "form-control form_datetime date", :placeholder => "Pick a time!"
          i class="fa fa-clock-o fa-fw input-group-addon"
      </p>
      <p>
        = s.submit "Scan Me!", :class => "btn btn-primary btn-lg btn-block"
      </p>

app/views/session/new.slim
div class="container sess"
  div class="page-header"
    h1 
      | Welcome to On Demand
  p 
    | Use of this application is limited to select members of SA-IT. If you feel that your department has a valid need for the services provided by Scan On Demand, then send us an email at 
    kbd
      | security@rescomp.berkeley.edu 
    | and we will get back to you within three working days.
  p If you are authorized to use Scan On Demand, you can login using CAS. Easy, right?
  p
    = link_to "Login!", login_path, class: "btn btn-primary btn-lg"

app/views/user/index.slim
div class="container"
    div class="panel panel-default"
      div class="panel-heading" 
        h3 class="panel-title" Authorized Users
      div class="panel-body"
       table class="table table-striped"
         thead
           tr
             th #
             th Name
             th Email
         tbody
           - @users.each do |u|
             tr
               td 
                 = u.id
               td 
                 = link_to u.name, user_path(u.id)
               td 
                 = u.email

app/views/user/show.slim
div class="container"
    div class="panel panel-default"
      div class="panel-heading" 
        h3 class="panel-title" Viewing Scan...
      div class="panel-body"
        table class="table"
          thead
            tr
              th Information
              th 
          tbody
            tr
              td
                strong Name
              td
                = @user.name
            tr
              td
                strong UID
              td
                = @user.calnet
    div class="panel panel-default"
      div class="panel-heading" 
        h3 class="panel-title" Requested Scans
      div class="panel-body"
       table class="table table-striped"
         thead
           tr
             th #
             th Address
             th Requestor
         tbody
           - @scans.each do |s|
             tr
               td 
                 = s.id
               td 
                 = link_to Address.find(s.targets).location, edit_scan_path(s)
               td 
                 - user = User.find_by_calnet(s.user)
                 = link_to user.name, user_path(user.id)